### ISSUE TITLE
Doubt about official_nms

### ISSUE THREAD

**Issue by moooises** [ibaiGorordo/ONNX-YOLOv7-Object-Detection#14]
Hello,
I'm studying how the export to .onnx and .trt works and found your [code](https://github.com/ibaiGorordo/ONNX-YOLOv7-Object-Detection/blob/main/yolov7/YOLOv7.py) that export the result of a .onnx file to a format that Yolov7 can read. It was very helpful, but I have some doubts about the nms (non maximum suppression). 

At first, I found that the detection boxes didn't display properly unless I set official_nms to True, I found an [issue ](https://github.com/ultralytics/yolov5/issues/343#issuecomment-658601548)in another project that said that too, but looking at the code It calls a nms function from the files yolov7.utils when official_nms is set to False. 

So, I would like to ask what is the purpose and meaning of the variable official_nms in the [code](https://github.com/ibaiGorordo/ONNX-YOLOv7-Object-Detection/blob/248dab0e87f0f1287da39ee9b1f3263f22205d6f/yolov7/YOLOv7.py). 
I still have doubts about it, but I have seen that you can add nms when you export a .pt file to .onnx files (You can see it in the [YoloV7 official repository](https://github.com/WongKinYiu/yolov7), in the export section ). Is the nms function used to apply nms when you don't apply it at the moment of exporting to .onnx or has any other purpose?

Thank you so much.

**Comment by ibaiGorordo** [comment]
Yes, as you mention, the nms function is only necessary when no postprocessing is implemented into the model. The issue is that there are different versions of how the postprocessing is implemented into the model. If you use the model with postprocessing exported from the official repository you will meed to set official_nms to true because the output data has a slightly different format.
